name: Daily Task

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello! This is a scheduled task."
